### LOGIN
POST http://localhost:3000/api/auth/signin
Accept: application/json
Content-Type: application/json

{
    "username": "admin@example.com",
    "password": "Password1$"
}

### GET ACCOUNTS
GET http://localhost:3000/api/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Accept: application/json

### GET ADMINSTRATORS
GET http://localhost:3000/api/admins/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Accept: application/json

### GET EMPLOYEES
GET http://localhost:3000/api/employees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Accept: application/json

### GET COMPANIES
GET http://localhost:3000/api/company/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Accept: application/json

### GET POSITIONS
GET http://localhost:3000/api/positions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Accept: application/json

#### REGISTER ADMIN
POST http://localhost:3000/api/signup/admins/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Content-Type: application/json
Accept: application/json

{
    "role": "ADMIN",
    "password": "Admin1234567890$",
    "name": "David Bello",
    "email": "admin@example.com"
}

#### REGISTER COMPANY
POST http://localhost:3000/api/signup/company/
Content-Type: application/json
Accept: application/json

{
    "role": "COMPANY",
    "country": "united-states",
    "address": "5673 Breakpoint Drive No. 98",
    "title": "Benny's Place",
    "taxid": "1234567890",
    "brief": "We provide expert legal representation, ensuring clients receive top-tier advocacy in corporate, criminal, and civil matters. Our experienced attorneys deliver strategic solutions, protecting your rights with professionalism and integrity. Whether in negotiations or courtrooms, we are committed to achieving the best outcomes for individuals and businesses alike",
    "password": "Password1$",
    "name": "Benny's Place",
    "email": "benny@example.com"
}

#### REGISTER COMPANY
POST http://localhost:3000/api/signup/company/
Content-Type: application/json
Accept: application/json

{
    "role": "COMPANY",
    "country": "united-states",
    "address": "5673 Breakpoint Drive No. 97",
    "title": "OpenSea Developments",
    "taxid": "2234567890",
    "brief": "We provide expert legal representation, ensuring clients receive top-tier advocacy in corporate, criminal, and civil matters. Our experienced attorneys deliver strategic solutions, protecting your rights with professionalism and integrity. Whether in negotiations or courtrooms, we are committed to achieving the best outcomes for individuals and businesses alike",
    "password": "Password1$",
    "name": "OpenSea Developments",
    "email": "opensea@example.com"
}

#### REGISTER EMPLOYEE
POST http://localhost:3000/api/signup/employees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Content-Type: application/json
Accept: application/json

{
    "role": "employee",
    "taxid": "0987654321",
    "username": "oluchibello",
    "country": "united-states",
    "address": "6033 Beachview Drive Apt 450",
    "gender": "female",
    "position": 1,
    "company": 1,
    "password": "Password1$",
    "name": "Oluchi Bello",
    "email": "oluchi@example.com"
}

#### ADD POSITION
POST http://localhost:3000/api/positions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJhY2NvdW50SWQiOjEsIm5hbWUiOiJhZG1pbiBhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NDM4MTE3NDQsImV4cCI6MTc0Mzg5ODE0NH0.Nq9IyZ8PtAccb2o1x-tolFF8sLkw0jZ1Vd9zFi72u28
Content-Type: application/json
Accept: application/json

{
    "description": "Develops and executes social media strategies to enhance brand awareness, engagement, and growth. They create and schedule content, analyze performance metrics, manage community interactions, and stay updated on trends to optimize campaigns. Strong creativity, communication, and analytical skills are essential for driving audience engagement and business success.",
    "title": "Social Media Manager",
    "salary": 5000,
    "currency": "USD",
    "company": 1
}