### GET ACCOUNTS
GET http://localhost:3000/api/accounts/

### GET ADMINSTRATORS
GET http://localhost:3000/api/administrators/

### GET EMPLOYEES
GET http://localhost:3000/api/employees/

### GET ORGANIZATIONS
GET http://localhost:3000/api/organizations/

### GET POSITIONS
GET http://localhost:3000/api/positions/

#### REGISTER ADMINISTRATOR
POST http://localhost:3000/api/register/administrator/
Content-Type: application/json
Accept: application/json

{
    "role": "administrator",
    "password": "Admin1234567890$",
    "name": "David Bello",
    "email": "david@example.com"
}

#### REGISTER ORGANIZATION
POST http://localhost:3000/api/register/organization/
Content-Type: application/json
Accept: application/json

{
    "role": "organization",
    "country": "united-states",
    "address": "5673 Breakpoint Drive No. 98",
    "title": "Benny's Place",
    "taxId": "1234567890",
    "brief": "We provide expert legal representation, ensuring clients receive top-tier advocacy in corporate, criminal, and civil matters. Our experienced attorneys deliver strategic solutions, protecting your rights with professionalism and integrity. Whether in negotiations or courtrooms, we are committed to achieving the best outcomes for individuals and businesses alike",
    "password": "Admin1234567890$",
    "name": "Benny's Place",
    "email": "benny@example.com"
}

#### REGISTER EMPLOYEE
POST http://localhost:3000/api/register/employee/
Content-Type: application/json
Accept: application/json

{
    "role": "employee",
    "taxId": "0987654321",
    "username": "oluchibello",
    "country": "united-states",
    "address": "6033 Beachview Drive Apt 450",
    "gender": "female",
    "position": 1,
    "organization": 1,
    "password": "Admin1234567890$",
    "name": "Oluchi Bello",
    "email": "oluchi@example.com"
}

#### ADD POSITION
POST http://localhost:3000/api/positions/
Content-Type: application/json
Accept: application/json

{
    "description": "Develops and executes social media strategies to enhance brand awareness, engagement, and growth. They create and schedule content, analyze performance metrics, manage community interactions, and stay updated on trends to optimize campaigns. Strong creativity, communication, and analytical skills are essential for driving audience engagement and business success.",
    "title": "Social Media Manager",
    "salary": 5000,
    "currency": "USD",
    "organization": 1
}