### GET ACCOUNTS
GET http://localhost:3000/api/accounts/


### GET ADMINSTRATORS
GET http://localhost:3000/api/administrators/


### GET EMPLOYEES
GET http://localhost:3000/api/employees/


### GET ORGANIZATIONS
GET http://localhost:3000/api/organizations/


#### REGISTER ADMINISTRATOR
POST http://localhost:3000/api/register/administrator/
Content-Type: application/json
Accept: application/json

{
    "role": "administrator",
    "password": "Admin1234567890$",
    "name": "Daniel Bello",
    "email": "daniel@example.com"
}

#### REGISTER ORGANIZATION
POST http://localhost:3000/api/register/organization/
